/*
 * Author   : Bharadwaj
 * Purpose  : Gives abstract view of all the business logics / functionality implemented on Case Histrory.
 * 
 * Revision CR Number   Release No  Date            Modified By     Description
 * -------- ---------   ----------  -----------     ------------    -----------
 *          17737       FY20-0802   07-Jul-2019       Fenny          Trigger refactoring
 * 
 * 
 */ 

public class CaseHistTriggerHandler extends TriggerHandler { 

   // public CaseRecordSelector casRecordSelector;
   // public override void getRecordSelector() {
   //     casRecordSelector = new CaseRecordSelector(Trigger.new, Trigger.oldMap, this);
   // }   
    
    /*
    public override void onAfterUpdate() {  
   
       CaseSLAUtilities.updateAggrValToCase(Trigger.new, (map<Id, Case_Status_History__c>)Trigger.oldMap);
       
         
    } 
     public override void onAfterInsert() { 
        
        CaseSLAUtilities.updtSlaValsInCase(Trigger.new);

     }*/

}