/*
 * Author   : Krishna
 * Purpose  : TriggerHandler for ContentDocmentLink Which handles file attachment on Opportunity and Support Request
 * 
 * Revision CR Number   Release No    Date            Modified By     Description
 * -------- ---------   ----------    -----------     ------------    -----------
 * 1.0      15108       FY18-DCS-0203 09-Nov-2017     Krishnakumar    PSA006 - Files to myDeal - create logic
 * 2.0      17739       FY20-0802       08-Jul-2019     Fenny           Trigger refactoring
 * 
 * NOTE: Strictly NO business logics inside this trigger.
 */
public class ContentDocLinkTriggerHandler extends TriggerHandler {
/*
	public override void onAfterInsert() {
        MyDealFileIntegration.processContentDocumentLinksInsert(trigger.new);
    }

    public override void onBeforeDelete() {
        MyDealFileIntegration.processContentDocumentLinksDelete(trigger.old);
    }*/
}