/*
 * Author   :Srikanth Ganji
 * Purpose  : Trigger.
 * 
 * Revision CR Number   Release No  Date            Modified By     Description
 * -------- ---------   ----------  -----------     ------------    -----------
 *  2.0     17789       FY20-0802   16-Jul-2019     Fenny           Trigger refactoring
 *
 * NOTE: Strictly NO business logics inside this trigger.
 */
public class DellEMCKeyContactTriggerHandler extends TriggerHandler {
    /*
    
    public override void onAfterUpdate() {
    // After successfully updation
    System.debug('On After Update');
        ServicesTriggerRelatedHelper.updateEMCOperationDEllEMCKeyContacts((List<DellEMC_Key_Contacts__c>)trigger.new);
       
    }
*/

}